contact_links:
  - name: ğŸ› Report a bug
    url: https://github.com/zoonk/zoonk/issues/new
    about: Report a bug that needs to be fixed.

  - name: ğŸ’¡ Make a suggestion
    url: https://github.com/zoonk/zoonk/discussions/new?category=ideas
    about: Share ideas or feature requests.

  - name: ğŸ™ Ask a question
    url: https://github.com/zoonk/zoonk/discussions/new?category=questions
    about: Ask any questions you have.
